default:
  image: rustdocker/rust:nightly
  tags: main.docker

build-job:
  stage: build
  script:
    - /root/.cargo/bin/cargo build --release

test-all:
  stage: test
  script:
    - /root/.cargo/bin/cargo test
