default:
  tags: 
    - blang

build-job:
  stage: build
  script:
    - /root/.cargo/bin/cargo build --release

test-all:
  stage: test
  script:
    - docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
  coverage: '/^\d+.\d+% coverage/'

