default:
  tags: 
    - blang

test-all:
  stage: test
  script:
    - docker run --security-opt seccomp=unconfined -v "/builds/$RUNNER_TOKEN_KEY/$CONCURRENT_ID/$NAMESPACE/$PROJECT_NAME:/volume" xd009642/tarpaulin
  coverage: '/^\d+.\d+% coverage/'

