[package]
name = "blox"
version = "0.1.0"
edition = "2021"


[profile.release]
debug = true
lto = "fat"      # Enable Link Time Optimization, massive performance improvement
#panic="abort"   # This disables the default "unwind" feature and looks like ignores 'expect' which had 20% in the profiler